#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci batch <<-EOF
		set luci.themes.Rosy=/luci-static/rosy
		set luci.main.mediaurlbase=/luci-static/rosy
		commit luci
	EOF
fi
rm /usr/lib/lua/luci/controller/opkg.lua
exit 0
